services:
  prometheus:
    ports:
      - 9090:9090
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - dpmp

  dpmp:
    container_name: DPMP
    image: dpmp
    restart: always
    ports:
      - 8080:8080
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysqldb
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_PORT=3306
      - MYSQL_USER=flavio
      - MYSQL_PASSWORD=gon1ometr1a
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 200M

  some-mongo:
    container_name: mymongo
    image: "mongo:5.0.10"
    restart: always
    ports:
      - 27017:27017

  mysqldb:
    container_name: mysqldb
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=People
      - MYSQL_USER=flavio
      - MYSQL_PASSWORD=gon1ometr1a